all: \
	docker/.Dockerfile.stamp \
	docker/pyenv/.Dockerfile.stamp \
	docker/pyenv/.Dockerfile-pyenvs.stamp \
	docker/django__django/.Dockerfile.stamp \
	docker/django__django/4.1/.Dockerfile.stamp \
	docker/django__django/5.0/.Dockerfile.stamp \
	docker/django__django/4.0/.Dockerfile.stamp \
	docker/django__django/3.0/.Dockerfile.stamp \
	docker/django__django/4.2/.Dockerfile.stamp \
	docker/django__django/3.1/.Dockerfile.stamp \
	docker/django__django/3.2/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/3.5/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/3.3/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/3.4/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/4.0/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/3.2/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/3.1/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/7.1/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/5.0/.Dockerfile.stamp \
	docker/sphinx-doc__sphinx/5.1/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.20/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10508/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10949/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11281/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11040/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10297/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13142/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13584/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-12471/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13496/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13241/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13497/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13439/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-13779/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14087/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14092/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14983/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15535/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15512/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14894/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/1.3/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25570/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25747/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25638/.Dockerfile.stamp \
	docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25500/.Dockerfile.stamp \
	docker/sympy__sympy/.Dockerfile.stamp \
	docker/sympy__sympy/1.1/.Dockerfile.stamp \
	docker/sympy__sympy/1.9/.Dockerfile.stamp \
	docker/sympy__sympy/1.5/.Dockerfile.stamp \
	docker/sympy__sympy/1.7/.Dockerfile.stamp \
	docker/sympy__sympy/1.0/.Dockerfile.stamp \
	docker/sympy__sympy/1.8/.Dockerfile.stamp \
	docker/sympy__sympy/1.12/.Dockerfile.stamp \
	docker/sympy__sympy/1.6/.Dockerfile.stamp \
	docker/sympy__sympy/1.4/.Dockerfile.stamp \
	docker/sympy__sympy/1.11/.Dockerfile.stamp \
	docker/sympy__sympy/1.2/.Dockerfile.stamp \
	docker/sympy__sympy/1.10/.Dockerfile.stamp \
	docker/sympy__sympy/1.13/.Dockerfile.stamp \
	docker/pytest-dev__pytest/.Dockerfile.stamp \
	docker/pytest-dev__pytest/4.4/.Dockerfile.stamp \
	docker/pytest-dev__pytest/8.0/.Dockerfile.stamp \
	docker/pytest-dev__pytest/7.0/.Dockerfile.stamp \
	docker/pytest-dev__pytest/5.4/.Dockerfile.stamp \
	docker/pytest-dev__pytest/5.0/.Dockerfile.stamp \
	docker/pytest-dev__pytest/4.5/.Dockerfile.stamp \
	docker/pytest-dev__pytest/6.3/.Dockerfile.stamp \
	docker/pytest-dev__pytest/4.6/.Dockerfile.stamp \
	docker/pytest-dev__pytest/5.2/.Dockerfile.stamp \
	docker/pytest-dev__pytest/6.0/.Dockerfile.stamp \
	docker/matplotlib__matplotlib/.Dockerfile.stamp \
	docker/matplotlib__matplotlib/3.5/.Dockerfile.stamp \
	docker/matplotlib__matplotlib/3.6/.Dockerfile.stamp \
	docker/matplotlib__matplotlib/3.3/.Dockerfile.stamp \
	docker/matplotlib__matplotlib/3.7/.Dockerfile.stamp \
	docker/astropy__astropy/.Dockerfile.stamp \
	docker/astropy__astropy/4.3/.Dockerfile.stamp \
	docker/astropy__astropy/5.1/.Dockerfile.stamp \
	docker/astropy__astropy/1.3/.Dockerfile.stamp \
	docker/astropy__astropy/5.2/.Dockerfile.stamp \
	docker/pydata__xarray/.Dockerfile.stamp \
	docker/pydata__xarray/0.12/.Dockerfile.stamp \
	docker/mwaskom__seaborn/.Dockerfile.stamp \
	docker/mwaskom__seaborn/0.12/.Dockerfile.stamp \
	docker/mwaskom__seaborn/0.13/.Dockerfile.stamp \
	docker/psf__requests/.Dockerfile.stamp \
	docker/psf__requests/0.14/.Dockerfile.stamp \
	docker/psf__requests/2.4/.Dockerfile.stamp \
	docker/psf__requests/2.7/.Dockerfile.stamp \
	docker/psf__requests/2.3/.Dockerfile.stamp \
	docker/psf__requests/2.10/.Dockerfile.stamp \
	docker/pylint-dev__pylint/.Dockerfile.stamp \
	docker/pylint-dev__pylint/2.15/.Dockerfile.stamp \
	docker/pylint-dev__pylint/2.14/.Dockerfile.stamp \
	docker/pylint-dev__pylint/2.13/.Dockerfile.stamp \
	docker/pallets__flask/.Dockerfile.stamp \
	docker/pallets__flask/2.0/.Dockerfile.stamp \
	docker/pallets__flask/2.3/.Dockerfile.stamp \
	$(NULL)

docker/.Dockerfile.stamp: docker/Dockerfile
	docker build --network=host -t aorwall/swe-bench-conda:bookworm-slim -f docker/Dockerfile .
	touch docker/.Dockerfile.stamp

docker/pyenv/.Dockerfile.stamp: docker/pyenv/Dockerfile docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pyenv:bookworm-slim -f docker/pyenv/Dockerfile .
	touch docker/pyenv/.Dockerfile.stamp

docker/pyenv/.Dockerfile-pyenvs.stamp: docker/pyenv/Dockerfile-pyenvs docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pyenvs:bookworm-slim -f docker/pyenv/Dockerfile-pyenvs .
	touch docker/pyenv/.Dockerfile-pyenvs.stamp

docker/django__django/.Dockerfile.stamp: docker/django__django/Dockerfile docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-django_django:bookworm-slim -f docker/django__django/Dockerfile .
	touch docker/django__django/.Dockerfile.stamp

docker/django__django/4.1/.Dockerfile.stamp: docker/django__django/4.1/Dockerfile docker/django__django/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-django_django-testbed:4.1 -f docker/django__django/4.1/Dockerfile .
	touch docker/django__django/4.1/.Dockerfile.stamp

docker/django__django/5.0/.Dockerfile.stamp: docker/django__django/5.0/Dockerfile docker/django__django/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-django_django-testbed:5.0 -f docker/django__django/5.0/Dockerfile .
	touch docker/django__django/5.0/.Dockerfile.stamp

docker/django__django/4.0/.Dockerfile.stamp: docker/django__django/4.0/Dockerfile docker/django__django/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-django_django-testbed:4.0 -f docker/django__django/4.0/Dockerfile .
	touch docker/django__django/4.0/.Dockerfile.stamp

docker/django__django/3.0/.Dockerfile.stamp: docker/django__django/3.0/Dockerfile docker/django__django/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-django_django-testbed:3.0 -f docker/django__django/3.0/Dockerfile .
	touch docker/django__django/3.0/.Dockerfile.stamp

docker/django__django/4.2/.Dockerfile.stamp: docker/django__django/4.2/Dockerfile docker/django__django/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-django_django-testbed:4.2 -f docker/django__django/4.2/Dockerfile .
	touch docker/django__django/4.2/.Dockerfile.stamp

docker/django__django/3.1/.Dockerfile.stamp: docker/django__django/3.1/Dockerfile docker/django__django/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-django_django-testbed:3.1 -f docker/django__django/3.1/Dockerfile .
	touch docker/django__django/3.1/.Dockerfile.stamp

docker/django__django/3.2/.Dockerfile.stamp: docker/django__django/3.2/Dockerfile docker/django__django/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-django_django-testbed:3.2 -f docker/django__django/3.2/Dockerfile .
	touch docker/django__django/3.2/.Dockerfile.stamp

docker/sphinx-doc__sphinx/.Dockerfile.stamp: docker/sphinx-doc__sphinx/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx:bookworm-slim -f docker/sphinx-doc__sphinx/Dockerfile .
	touch docker/sphinx-doc__sphinx/.Dockerfile.stamp

docker/sphinx-doc__sphinx/3.5/.Dockerfile.stamp: docker/sphinx-doc__sphinx/3.5/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:3.5 -f docker/sphinx-doc__sphinx/3.5/Dockerfile .
	touch docker/sphinx-doc__sphinx/3.5/.Dockerfile.stamp

docker/sphinx-doc__sphinx/3.3/.Dockerfile.stamp: docker/sphinx-doc__sphinx/3.3/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:3.3 -f docker/sphinx-doc__sphinx/3.3/Dockerfile .
	touch docker/sphinx-doc__sphinx/3.3/.Dockerfile.stamp

docker/sphinx-doc__sphinx/3.4/.Dockerfile.stamp: docker/sphinx-doc__sphinx/3.4/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:3.4 -f docker/sphinx-doc__sphinx/3.4/Dockerfile .
	touch docker/sphinx-doc__sphinx/3.4/.Dockerfile.stamp

docker/sphinx-doc__sphinx/4.0/.Dockerfile.stamp: docker/sphinx-doc__sphinx/4.0/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:4.0 -f docker/sphinx-doc__sphinx/4.0/Dockerfile .
	touch docker/sphinx-doc__sphinx/4.0/.Dockerfile.stamp

docker/sphinx-doc__sphinx/3.2/.Dockerfile.stamp: docker/sphinx-doc__sphinx/3.2/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:3.2 -f docker/sphinx-doc__sphinx/3.2/Dockerfile .
	touch docker/sphinx-doc__sphinx/3.2/.Dockerfile.stamp

docker/sphinx-doc__sphinx/3.1/.Dockerfile.stamp: docker/sphinx-doc__sphinx/3.1/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:3.1 -f docker/sphinx-doc__sphinx/3.1/Dockerfile .
	touch docker/sphinx-doc__sphinx/3.1/.Dockerfile.stamp

docker/sphinx-doc__sphinx/7.1/.Dockerfile.stamp: docker/sphinx-doc__sphinx/7.1/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:7.1 -f docker/sphinx-doc__sphinx/7.1/Dockerfile .
	touch docker/sphinx-doc__sphinx/7.1/.Dockerfile.stamp

docker/sphinx-doc__sphinx/5.0/.Dockerfile.stamp: docker/sphinx-doc__sphinx/5.0/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:5.0 -f docker/sphinx-doc__sphinx/5.0/Dockerfile .
	touch docker/sphinx-doc__sphinx/5.0/.Dockerfile.stamp

docker/sphinx-doc__sphinx/5.1/.Dockerfile.stamp: docker/sphinx-doc__sphinx/5.1/Dockerfile docker/sphinx-doc__sphinx/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sphinx-doc_sphinx-testbed:5.1 -f docker/sphinx-doc__sphinx/5.1/Dockerfile .
	touch docker/sphinx-doc__sphinx/5.1/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/Dockerfile docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn:bookworm-slim -f docker/scikit-learn__scikit-learn/Dockerfile .
	touch docker/scikit-learn__scikit-learn/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.20/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.20/Dockerfile docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-testbed:0.20 -f docker/scikit-learn__scikit-learn/0.20/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.20/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10508/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10508/Dockerfile docker/scikit-learn__scikit-learn/0.20/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-10508 -f docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10508/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10508/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10949/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10949/Dockerfile docker/scikit-learn__scikit-learn/0.20/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-10949 -f docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10949/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10949/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11281/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11281/Dockerfile docker/scikit-learn__scikit-learn/0.20/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-11281 -f docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11281/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11281/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11040/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11040/Dockerfile docker/scikit-learn__scikit-learn/0.20/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-11040 -f docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11040/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-11040/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10297/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10297/Dockerfile docker/scikit-learn__scikit-learn/0.20/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-10297 -f docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10297/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.20/scikit-learn__scikit-learn-10297/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.21/Dockerfile docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-testbed:0.21 -f docker/scikit-learn__scikit-learn/0.21/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13142/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13142/Dockerfile docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-13142 -f docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13142/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13142/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13584/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13584/Dockerfile docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-13584 -f docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13584/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13584/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-12471/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-12471/Dockerfile docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-12471 -f docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-12471/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-12471/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13496/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13496/Dockerfile docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-13496 -f docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13496/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13496/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13241/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13241/Dockerfile docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-13241 -f docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13241/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13241/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13497/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13497/Dockerfile docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-13497 -f docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13497/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13497/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13439/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13439/Dockerfile docker/scikit-learn__scikit-learn/0.21/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-13439 -f docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13439/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.21/scikit-learn__scikit-learn-13439/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.22/Dockerfile docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-testbed:0.22 -f docker/scikit-learn__scikit-learn/0.22/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-13779/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-13779/Dockerfile docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-13779 -f docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-13779/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-13779/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14087/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14087/Dockerfile docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-14087 -f docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14087/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14087/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14092/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14092/Dockerfile docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-14092 -f docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14092/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14092/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14983/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14983/Dockerfile docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-14983 -f docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14983/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14983/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15535/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15535/Dockerfile docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-15535 -f docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15535/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15535/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15512/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15512/Dockerfile docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-15512 -f docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15512/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-15512/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14894/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14894/Dockerfile docker/scikit-learn__scikit-learn/0.22/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-14894 -f docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14894/Dockerfile .
	touch docker/scikit-learn__scikit-learn/0.22/scikit-learn__scikit-learn-14894/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/1.3/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/1.3/Dockerfile docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-testbed:1.3 -f docker/scikit-learn__scikit-learn/1.3/Dockerfile .
	touch docker/scikit-learn__scikit-learn/1.3/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25570/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25570/Dockerfile docker/scikit-learn__scikit-learn/1.3/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-25570 -f docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25570/Dockerfile .
	touch docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25570/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25747/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25747/Dockerfile docker/scikit-learn__scikit-learn/1.3/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-25747 -f docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25747/Dockerfile .
	touch docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25747/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25638/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25638/Dockerfile docker/scikit-learn__scikit-learn/1.3/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-25638 -f docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25638/Dockerfile .
	touch docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25638/.Dockerfile.stamp

docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25500/.Dockerfile.stamp: docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25500/Dockerfile docker/scikit-learn__scikit-learn/1.3/.Dockerfile.stamp docker/scikit-learn__scikit-learn/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-scikit-learn_scikit-learn-instance:scikit-learn__scikit-learn-25500 -f docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25500/Dockerfile .
	touch docker/scikit-learn__scikit-learn/1.3/scikit-learn__scikit-learn-25500/.Dockerfile.stamp

docker/sympy__sympy/.Dockerfile.stamp: docker/sympy__sympy/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy:bookworm-slim -f docker/sympy__sympy/Dockerfile .
	touch docker/sympy__sympy/.Dockerfile.stamp

docker/sympy__sympy/1.1/.Dockerfile.stamp: docker/sympy__sympy/1.1/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.1 -f docker/sympy__sympy/1.1/Dockerfile .
	touch docker/sympy__sympy/1.1/.Dockerfile.stamp

docker/sympy__sympy/1.9/.Dockerfile.stamp: docker/sympy__sympy/1.9/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.9 -f docker/sympy__sympy/1.9/Dockerfile .
	touch docker/sympy__sympy/1.9/.Dockerfile.stamp

docker/sympy__sympy/1.5/.Dockerfile.stamp: docker/sympy__sympy/1.5/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.5 -f docker/sympy__sympy/1.5/Dockerfile .
	touch docker/sympy__sympy/1.5/.Dockerfile.stamp

docker/sympy__sympy/1.7/.Dockerfile.stamp: docker/sympy__sympy/1.7/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.7 -f docker/sympy__sympy/1.7/Dockerfile .
	touch docker/sympy__sympy/1.7/.Dockerfile.stamp

docker/sympy__sympy/1.0/.Dockerfile.stamp: docker/sympy__sympy/1.0/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.0 -f docker/sympy__sympy/1.0/Dockerfile .
	touch docker/sympy__sympy/1.0/.Dockerfile.stamp

docker/sympy__sympy/1.8/.Dockerfile.stamp: docker/sympy__sympy/1.8/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.8 -f docker/sympy__sympy/1.8/Dockerfile .
	touch docker/sympy__sympy/1.8/.Dockerfile.stamp

docker/sympy__sympy/1.12/.Dockerfile.stamp: docker/sympy__sympy/1.12/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.12 -f docker/sympy__sympy/1.12/Dockerfile .
	touch docker/sympy__sympy/1.12/.Dockerfile.stamp

docker/sympy__sympy/1.6/.Dockerfile.stamp: docker/sympy__sympy/1.6/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.6 -f docker/sympy__sympy/1.6/Dockerfile .
	touch docker/sympy__sympy/1.6/.Dockerfile.stamp

docker/sympy__sympy/1.4/.Dockerfile.stamp: docker/sympy__sympy/1.4/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.4 -f docker/sympy__sympy/1.4/Dockerfile .
	touch docker/sympy__sympy/1.4/.Dockerfile.stamp

docker/sympy__sympy/1.11/.Dockerfile.stamp: docker/sympy__sympy/1.11/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.11 -f docker/sympy__sympy/1.11/Dockerfile .
	touch docker/sympy__sympy/1.11/.Dockerfile.stamp

docker/sympy__sympy/1.2/.Dockerfile.stamp: docker/sympy__sympy/1.2/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.2 -f docker/sympy__sympy/1.2/Dockerfile .
	touch docker/sympy__sympy/1.2/.Dockerfile.stamp

docker/sympy__sympy/1.10/.Dockerfile.stamp: docker/sympy__sympy/1.10/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.10 -f docker/sympy__sympy/1.10/Dockerfile .
	touch docker/sympy__sympy/1.10/.Dockerfile.stamp

docker/sympy__sympy/1.13/.Dockerfile.stamp: docker/sympy__sympy/1.13/Dockerfile docker/sympy__sympy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-sympy_sympy-testbed:1.13 -f docker/sympy__sympy/1.13/Dockerfile .
	touch docker/sympy__sympy/1.13/.Dockerfile.stamp

docker/pytest-dev__pytest/.Dockerfile.stamp: docker/pytest-dev__pytest/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest:bookworm-slim -f docker/pytest-dev__pytest/Dockerfile .
	touch docker/pytest-dev__pytest/.Dockerfile.stamp

docker/pytest-dev__pytest/4.4/.Dockerfile.stamp: docker/pytest-dev__pytest/4.4/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:4.4 -f docker/pytest-dev__pytest/4.4/Dockerfile .
	touch docker/pytest-dev__pytest/4.4/.Dockerfile.stamp

docker/pytest-dev__pytest/8.0/.Dockerfile.stamp: docker/pytest-dev__pytest/8.0/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:8.0 -f docker/pytest-dev__pytest/8.0/Dockerfile .
	touch docker/pytest-dev__pytest/8.0/.Dockerfile.stamp

docker/pytest-dev__pytest/7.0/.Dockerfile.stamp: docker/pytest-dev__pytest/7.0/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:7.0 -f docker/pytest-dev__pytest/7.0/Dockerfile .
	touch docker/pytest-dev__pytest/7.0/.Dockerfile.stamp

docker/pytest-dev__pytest/5.4/.Dockerfile.stamp: docker/pytest-dev__pytest/5.4/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:5.4 -f docker/pytest-dev__pytest/5.4/Dockerfile .
	touch docker/pytest-dev__pytest/5.4/.Dockerfile.stamp

docker/pytest-dev__pytest/5.0/.Dockerfile.stamp: docker/pytest-dev__pytest/5.0/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:5.0 -f docker/pytest-dev__pytest/5.0/Dockerfile .
	touch docker/pytest-dev__pytest/5.0/.Dockerfile.stamp

docker/pytest-dev__pytest/4.5/.Dockerfile.stamp: docker/pytest-dev__pytest/4.5/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:4.5 -f docker/pytest-dev__pytest/4.5/Dockerfile .
	touch docker/pytest-dev__pytest/4.5/.Dockerfile.stamp

docker/pytest-dev__pytest/6.3/.Dockerfile.stamp: docker/pytest-dev__pytest/6.3/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:6.3 -f docker/pytest-dev__pytest/6.3/Dockerfile .
	touch docker/pytest-dev__pytest/6.3/.Dockerfile.stamp

docker/pytest-dev__pytest/4.6/.Dockerfile.stamp: docker/pytest-dev__pytest/4.6/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:4.6 -f docker/pytest-dev__pytest/4.6/Dockerfile .
	touch docker/pytest-dev__pytest/4.6/.Dockerfile.stamp

docker/pytest-dev__pytest/5.2/.Dockerfile.stamp: docker/pytest-dev__pytest/5.2/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:5.2 -f docker/pytest-dev__pytest/5.2/Dockerfile .
	touch docker/pytest-dev__pytest/5.2/.Dockerfile.stamp

docker/pytest-dev__pytest/6.0/.Dockerfile.stamp: docker/pytest-dev__pytest/6.0/Dockerfile docker/pytest-dev__pytest/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pytest-dev_pytest-testbed:6.0 -f docker/pytest-dev__pytest/6.0/Dockerfile .
	touch docker/pytest-dev__pytest/6.0/.Dockerfile.stamp

docker/matplotlib__matplotlib/.Dockerfile.stamp: docker/matplotlib__matplotlib/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-matplotlib_matplotlib:bookworm-slim -f docker/matplotlib__matplotlib/Dockerfile .
	touch docker/matplotlib__matplotlib/.Dockerfile.stamp

docker/matplotlib__matplotlib/3.5/.Dockerfile.stamp: docker/matplotlib__matplotlib/3.5/Dockerfile docker/matplotlib__matplotlib/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-matplotlib_matplotlib-testbed:3.5 -f docker/matplotlib__matplotlib/3.5/Dockerfile .
	touch docker/matplotlib__matplotlib/3.5/.Dockerfile.stamp

docker/matplotlib__matplotlib/3.6/.Dockerfile.stamp: docker/matplotlib__matplotlib/3.6/Dockerfile docker/matplotlib__matplotlib/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-matplotlib_matplotlib-testbed:3.6 -f docker/matplotlib__matplotlib/3.6/Dockerfile .
	touch docker/matplotlib__matplotlib/3.6/.Dockerfile.stamp

docker/matplotlib__matplotlib/3.3/.Dockerfile.stamp: docker/matplotlib__matplotlib/3.3/Dockerfile docker/matplotlib__matplotlib/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-matplotlib_matplotlib-testbed:3.3 -f docker/matplotlib__matplotlib/3.3/Dockerfile .
	touch docker/matplotlib__matplotlib/3.3/.Dockerfile.stamp

docker/matplotlib__matplotlib/3.7/.Dockerfile.stamp: docker/matplotlib__matplotlib/3.7/Dockerfile docker/matplotlib__matplotlib/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-matplotlib_matplotlib-testbed:3.7 -f docker/matplotlib__matplotlib/3.7/Dockerfile .
	touch docker/matplotlib__matplotlib/3.7/.Dockerfile.stamp

docker/astropy__astropy/.Dockerfile.stamp: docker/astropy__astropy/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-astropy_astropy:bookworm-slim -f docker/astropy__astropy/Dockerfile .
	touch docker/astropy__astropy/.Dockerfile.stamp

docker/astropy__astropy/4.3/.Dockerfile.stamp: docker/astropy__astropy/4.3/Dockerfile docker/astropy__astropy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-astropy_astropy-testbed:4.3 -f docker/astropy__astropy/4.3/Dockerfile .
	touch docker/astropy__astropy/4.3/.Dockerfile.stamp

docker/astropy__astropy/5.1/.Dockerfile.stamp: docker/astropy__astropy/5.1/Dockerfile docker/astropy__astropy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-astropy_astropy-testbed:5.1 -f docker/astropy__astropy/5.1/Dockerfile .
	touch docker/astropy__astropy/5.1/.Dockerfile.stamp

docker/astropy__astropy/1.3/.Dockerfile.stamp: docker/astropy__astropy/1.3/Dockerfile docker/astropy__astropy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-astropy_astropy-testbed:1.3 -f docker/astropy__astropy/1.3/Dockerfile .
	touch docker/astropy__astropy/1.3/.Dockerfile.stamp

docker/astropy__astropy/5.2/.Dockerfile.stamp: docker/astropy__astropy/5.2/Dockerfile docker/astropy__astropy/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-astropy_astropy-testbed:5.2 -f docker/astropy__astropy/5.2/Dockerfile .
	touch docker/astropy__astropy/5.2/.Dockerfile.stamp

docker/pydata__xarray/.Dockerfile.stamp: docker/pydata__xarray/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pydata_xarray:bookworm-slim -f docker/pydata__xarray/Dockerfile .
	touch docker/pydata__xarray/.Dockerfile.stamp

docker/pydata__xarray/0.12/.Dockerfile.stamp: docker/pydata__xarray/0.12/Dockerfile docker/pydata__xarray/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pydata_xarray-testbed:0.12 -f docker/pydata__xarray/0.12/Dockerfile .
	touch docker/pydata__xarray/0.12/.Dockerfile.stamp

docker/mwaskom__seaborn/.Dockerfile.stamp: docker/mwaskom__seaborn/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-mwaskom_seaborn:bookworm-slim -f docker/mwaskom__seaborn/Dockerfile .
	touch docker/mwaskom__seaborn/.Dockerfile.stamp

docker/mwaskom__seaborn/0.12/.Dockerfile.stamp: docker/mwaskom__seaborn/0.12/Dockerfile docker/mwaskom__seaborn/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-mwaskom_seaborn-testbed:0.12 -f docker/mwaskom__seaborn/0.12/Dockerfile .
	touch docker/mwaskom__seaborn/0.12/.Dockerfile.stamp

docker/mwaskom__seaborn/0.13/.Dockerfile.stamp: docker/mwaskom__seaborn/0.13/Dockerfile docker/mwaskom__seaborn/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-mwaskom_seaborn-testbed:0.13 -f docker/mwaskom__seaborn/0.13/Dockerfile .
	touch docker/mwaskom__seaborn/0.13/.Dockerfile.stamp

docker/psf__requests/.Dockerfile.stamp: docker/psf__requests/Dockerfile docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-psf_requests:bookworm-slim -f docker/psf__requests/Dockerfile .
	touch docker/psf__requests/.Dockerfile.stamp

docker/psf__requests/0.14/.Dockerfile.stamp: docker/psf__requests/0.14/Dockerfile docker/psf__requests/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-psf_requests-testbed:0.14 -f docker/psf__requests/0.14/Dockerfile .
	touch docker/psf__requests/0.14/.Dockerfile.stamp

docker/psf__requests/2.4/.Dockerfile.stamp: docker/psf__requests/2.4/Dockerfile docker/psf__requests/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-psf_requests-testbed:2.4 -f docker/psf__requests/2.4/Dockerfile .
	touch docker/psf__requests/2.4/.Dockerfile.stamp

docker/psf__requests/2.7/.Dockerfile.stamp: docker/psf__requests/2.7/Dockerfile docker/psf__requests/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-psf_requests-testbed:2.7 -f docker/psf__requests/2.7/Dockerfile .
	touch docker/psf__requests/2.7/.Dockerfile.stamp

docker/psf__requests/2.3/.Dockerfile.stamp: docker/psf__requests/2.3/Dockerfile docker/psf__requests/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-psf_requests-testbed:2.3 -f docker/psf__requests/2.3/Dockerfile .
	touch docker/psf__requests/2.3/.Dockerfile.stamp

docker/psf__requests/2.10/.Dockerfile.stamp: docker/psf__requests/2.10/Dockerfile docker/psf__requests/.Dockerfile.stamp docker/pyenv/.Dockerfile-pyenvs.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-psf_requests-testbed:2.10 -f docker/psf__requests/2.10/Dockerfile .
	touch docker/psf__requests/2.10/.Dockerfile.stamp

docker/pylint-dev__pylint/.Dockerfile.stamp: docker/pylint-dev__pylint/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pylint-dev_pylint:bookworm-slim -f docker/pylint-dev__pylint/Dockerfile .
	touch docker/pylint-dev__pylint/.Dockerfile.stamp

docker/pylint-dev__pylint/2.15/.Dockerfile.stamp: docker/pylint-dev__pylint/2.15/Dockerfile docker/pylint-dev__pylint/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pylint-dev_pylint-testbed:2.15 -f docker/pylint-dev__pylint/2.15/Dockerfile .
	touch docker/pylint-dev__pylint/2.15/.Dockerfile.stamp

docker/pylint-dev__pylint/2.14/.Dockerfile.stamp: docker/pylint-dev__pylint/2.14/Dockerfile docker/pylint-dev__pylint/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pylint-dev_pylint-testbed:2.14 -f docker/pylint-dev__pylint/2.14/Dockerfile .
	touch docker/pylint-dev__pylint/2.14/.Dockerfile.stamp

docker/pylint-dev__pylint/2.13/.Dockerfile.stamp: docker/pylint-dev__pylint/2.13/Dockerfile docker/pylint-dev__pylint/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pylint-dev_pylint-testbed:2.13 -f docker/pylint-dev__pylint/2.13/Dockerfile .
	touch docker/pylint-dev__pylint/2.13/.Dockerfile.stamp

docker/pallets__flask/.Dockerfile.stamp: docker/pallets__flask/Dockerfile docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pallets_flask:bookworm-slim -f docker/pallets__flask/Dockerfile .
	touch docker/pallets__flask/.Dockerfile.stamp

docker/pallets__flask/2.0/.Dockerfile.stamp: docker/pallets__flask/2.0/Dockerfile docker/pallets__flask/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pallets_flask-testbed:2.0 -f docker/pallets__flask/2.0/Dockerfile .
	touch docker/pallets__flask/2.0/.Dockerfile.stamp

docker/pallets__flask/2.3/.Dockerfile.stamp: docker/pallets__flask/2.3/Dockerfile docker/pallets__flask/.Dockerfile.stamp docker/pyenv/.Dockerfile.stamp docker/.Dockerfile.stamp
	docker build --network=host -t aorwall/swe-bench-pallets_flask-testbed:2.3 -f docker/pallets__flask/2.3/Dockerfile .
	touch docker/pallets__flask/2.3/.Dockerfile.stamp
